version: "3"

services:
  pacman:
    image: deweiliu/pacman
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    container_name: pacman-canvas-container
